---
- hosts: localhost
  collections:
    - kubernetes.core
  vars_files:
    - vars/kubernetes.yml
  tasks:
    - name: Defining postgress (db) service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: pg-db
            namespace: default
            labels:
              app: database
          spec:
            selector:
              app: database
            type: ClusterIP
            ports:
              - protocol: TCP
                port: 5432
                targetPort: 5432
    - name: Create postgres StatefulSet
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: pg-db
            namespace: default
            labels:
              app: database
          spec:
            replicas: 1
            serviceName: db
            selector:
              matchLabels:
                app: database
            template:
              metadata:
                labels:
                  app: database
              spec:
                containers:
                  - name: postgres-cont
                    # image: docker.io/library/postgres:latest
                    image: "{{ registry_host }}/postgres:latest"
                    ports:
                      - containerPort: 5432
                        name: psql
                        protocol: TCP
                    env: 
                      - name: POSTGRES_PASSWORD
                        value: "password"
